# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(560, 700))
        MainWindow.setMaximumSize(QtCore.QSize(560, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{background:#151821;color:#f5f7fb;font:11pt \"Segoe UI\";}\n"
"QPushButton{background:#2b3245;border:1px solid #3d4963;border-radius:12px;padding:10px 14px;font-weight:600;}\n"
"QPushButton:hover{background:#36415b;}\n"
"QListWidget{background:#1b2130;border:1px solid #313b52;border-radius:16px;padding:10px;outline:none;}\n"
"QListWidget::item{padding:10px 12px;border-radius:10px;margin:2px 0;}\n"
"QListWidget::item:hover{background:#2a3449;}\n"
"QListWidget::item:selected{background:#6d7cff;color:white;}\n"
"QGroupBox{background:#171c2b;border:1px solid #252d41;border-radius:20px;margin-top:18px;padding-top:18px;font:700 10pt \"Segoe UI Semibold\";}\n"
"QGroupBox::title{subcontrol-origin: margin;left:16px;padding:0 6px;color:#cfd7ea;}\n"
"QComboBox,QSlider,QCheckBox{background:transparent;}\n"
"QComboBox{background:#1b2130;border:1px solid #313b52;border-radius:12px;padding:8px 12px;}\n"
"QComboBox QAbstractItemView{background:#1b2130;border:1px solid #313b52;selection-background-color:#6d7cff;}\n"
"QCheckBox{spacing:10px;}\n"
"QCheckBox::indicator{width:18px;height:18px;}\n"
"QCheckBox::indicator:unchecked{border:1px solid #4a5673;border-radius:6px;background:#1b2130;}\n"
"QCheckBox::indicator:checked{border:1px solid #6d7cff;border-radius:6px;background:#6d7cff;}\n"
"QSlider::groove:horizontal{height:8px;background:#283146;border-radius:4px;}\n"
"QSlider::sub-page:horizontal{background:#6d7cff;border-radius:4px;}\n"
"QSlider::handle:horizontal{background:#eef2ff;border:2px solid #6d7cff;width:18px;height:18px;margin:-6px 0;border-radius:9px;}\n"
"QLabel{background:transparent;}\n"
"QScrollBar:vertical{background:transparent;width:12px;margin:4px;}\n"
"QScrollBar::handle:vertical{background:#36415b;border-radius:6px;min-height:24px;}\n"
"QScrollBar::add-line:vertical,QScrollBar::sub-line:vertical,QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical{background:none;border:none;}\n"
"#background{background:#101522;border-bottom:1px solid #252d41;}\n"
"#title{font:700 18pt \"Segoe UI Semibold\";}\n"
"#subtitle{color:#98a4bf;font:10pt \"Segoe UI\";}\n"
"#exit_button,#min_button{background:transparent;border:none;border-radius:12px;padding:8px 12px;}\n"
"#min_button:hover{background:#20283a;}\n"
"#exit_button:hover{background:#4a1f28;color:#ffd7dd;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(506, 12, 40, 40))
        self.exit_button.setStyleSheet("")
        self.exit_button.setObjectName("exit_button")
        self.min_button = QtWidgets.QPushButton(self.centralwidget)
        self.min_button.setGeometry(QtCore.QRect(460, 12, 40, 40))
        self.min_button.setStyleSheet("")
        self.min_button.setObjectName("min_button")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(28, 126, 504, 206))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(16, 16, 16, 16)
        self.gridLayout.setHorizontalSpacing(18)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.pref_over = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over.setStyleSheet("background:none")
        self.pref_over.setObjectName("pref_over")
        self.gridLayout.addWidget(self.pref_over, 0, 0, 1, 1)
        self.pref_over_el5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over_el5.setObjectName("pref_over_el5")
        self.gridLayout.addWidget(self.pref_over_el5, 5, 0, 1, 1)
        self.pref_over_el2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over_el2.setObjectName("pref_over_el2")
        self.gridLayout.addWidget(self.pref_over_el2, 2, 0, 1, 1)
        self.select_move_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.select_move_down.setObjectName("select_move_down")
        self.gridLayout.addWidget(self.select_move_down, 2, 1, 1, 1)
        self.select_move_right = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.select_move_right.setObjectName("select_move_right")
        self.gridLayout.addWidget(self.select_move_right, 4, 1, 1, 1)
        self.select_move_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.select_move_up.setObjectName("select_move_up")
        self.gridLayout.addWidget(self.select_move_up, 1, 1, 1, 1)
        self.pref_over_el3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over_el3.setObjectName("pref_over_el3")
        self.gridLayout.addWidget(self.pref_over_el3, 3, 0, 1, 1)
        self.stop_sound = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.stop_sound.setObjectName("stop_sound")
        self.gridLayout.addWidget(self.stop_sound, 6, 1, 1, 1)
        self.pref_over_el6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over_el6.setObjectName("pref_over_el6")
        self.gridLayout.addWidget(self.pref_over_el6, 6, 0, 1, 1)
        self.pref_over_el4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over_el4.setObjectName("pref_over_el4")
        self.gridLayout.addWidget(self.pref_over_el4, 4, 0, 1, 1)
        self.select_move_left = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.select_move_left.setObjectName("select_move_left")
        self.gridLayout.addWidget(self.select_move_left, 3, 1, 1, 1)
        self.pref_over_el1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pref_over_el1.setObjectName("pref_over_el1")
        self.gridLayout.addWidget(self.pref_over_el1, 1, 0, 1, 1)
        self.play_sound = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.play_sound.setObjectName("play_sound")
        self.gridLayout.addWidget(self.play_sound, 5, 1, 1, 1)
        self.background = QtWidgets.QWidget(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 560, 76))
        self.background.setStyleSheet("")
        self.background.setObjectName("background")
        self.title = QtWidgets.QLabel(self.background)
        self.title.setGeometry(QtCore.QRect(28, 10, 220, 30))
        self.title.setStyleSheet("")
        self.title.setObjectName("title")
        self.subtitle = QtWidgets.QLabel(self.background)
        self.subtitle.setGeometry(QtCore.QRect(28, 40, 280, 20))
        self.subtitle.setObjectName("subtitle")
        self.pref_themes = QtWidgets.QLabel(self.centralwidget)
        self.pref_themes.setGeometry(QtCore.QRect(28, 576, 140, 24))
        self.pref_themes.setObjectName("pref_themes")
        self.themesList = QtWidgets.QListWidget(self.centralwidget)
        self.themesList.setGeometry(QtCore.QRect(28, 608, 504, 72))
        
        # Add Audio Devices Section
        self.audioGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.audioGroupBox.setGeometry(QtCore.QRect(28, 344, 504, 220))
        self.audioGroupBox.setObjectName("audioGroupBox")
        self.audioGroupBox.setTitle("Audio Devices")
        
        self.inputDeviceLabel = QtWidgets.QLabel(self.audioGroupBox)
        self.inputDeviceLabel.setGeometry(QtCore.QRect(18, 38, 80, 24))
        self.inputDeviceLabel.setText("Input:")
        
        self.inputDeviceCombo = QtWidgets.QComboBox(self.audioGroupBox)
        self.inputDeviceCombo.setGeometry(QtCore.QRect(110, 32, 376, 36))
        
        self.outputDeviceLabel = QtWidgets.QLabel(self.audioGroupBox)
        self.outputDeviceLabel.setGeometry(QtCore.QRect(18, 82, 80, 24))
        self.outputDeviceLabel.setText("Output:")
        
        self.outputDeviceCombo = QtWidgets.QComboBox(self.audioGroupBox)
        self.outputDeviceCombo.setGeometry(QtCore.QRect(110, 76, 376, 36))
        
        self.refreshDevicesBtn = QtWidgets.QPushButton(self.audioGroupBox)
        self.refreshDevicesBtn.setGeometry(QtCore.QRect(18, 124, 468, 38))
        self.refreshDevicesBtn.setText("Refresh Devices")

        self.micPassthroughCheck = QtWidgets.QCheckBox(self.audioGroupBox)
        self.micPassthroughCheck.setGeometry(QtCore.QRect(18, 170, 280, 24))
        self.micPassthroughCheck.setObjectName("micPassthroughCheck")

        self.micVolumeLabel = QtWidgets.QLabel(self.audioGroupBox)
        self.micVolumeLabel.setGeometry(QtCore.QRect(18, 192, 90, 24))
        self.micVolumeLabel.setObjectName("micVolumeLabel")

        self.micVolumeSlider = QtWidgets.QSlider(self.audioGroupBox)
        self.micVolumeSlider.setGeometry(QtCore.QRect(110, 188, 320, 28))
        self.micVolumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.micVolumeSlider.setMinimum(0)
        self.micVolumeSlider.setMaximum(200)
        self.micVolumeSlider.setProperty("value", 100)
        self.micVolumeSlider.setObjectName("micVolumeSlider")

        self.micVolumeValue = QtWidgets.QLabel(self.audioGroupBox)
        self.micVolumeValue.setGeometry(QtCore.QRect(436, 192, 50, 24))
        self.micVolumeValue.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.micVolumeValue.setObjectName("micVolumeValue")

        self.controlsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.controlsGroupBox.setGeometry(QtCore.QRect(28, 88, 504, 244))
        self.controlsGroupBox.setTitle("Overlay Controls")
        self.controlsGroupBox.setObjectName("controlsGroupBox")
        self.gridLayoutWidget.setParent(self.controlsGroupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 8, 504, 220))

        self.themesList.setObjectName("themesList")
        self.background.raise_()
        self.exit_button.raise_()
        self.min_button.raise_()
        self.controlsGroupBox.raise_()
        self.audioGroupBox.raise_()
        self.pref_themes.raise_()
        self.themesList.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Preferences"))
        self.exit_button.setText(_translate("MainWindow", "X"))
        self.min_button.setText(_translate("MainWindow", "-"))
        self.pref_over.setText(_translate("MainWindow", "Overlay control"))
        self.pref_over_el5.setText(_translate("MainWindow", "Overlay play sound"))
        self.pref_over_el2.setText(_translate("MainWindow", "Overlay menu down"))
        self.select_move_down.setText(_translate("MainWindow", "PushButton"))
        self.select_move_right.setText(_translate("MainWindow", "PushButton"))
        self.select_move_up.setText(_translate("MainWindow", "PushButton"))
        self.pref_over_el3.setText(_translate("MainWindow", "Overlay menu left"))
        self.stop_sound.setText(_translate("MainWindow", "PushButton"))
        self.pref_over_el6.setText(_translate("MainWindow", "Overlay stop sound"))
        self.pref_over_el4.setText(_translate("MainWindow", "Overlay menu right"))
        self.select_move_left.setText(_translate("MainWindow", "PushButton"))
        self.pref_over_el1.setText(_translate("MainWindow", "Overlay menu up"))
        self.play_sound.setText(_translate("MainWindow", "PushButton"))
        self.title.setText(_translate("MainWindow", "Preferences"))
        self.subtitle.setText(_translate("MainWindow", "Controls, devices and themes"))
        self.pref_themes.setText(_translate("MainWindow", "Themes"))
        self.micPassthroughCheck.setText(_translate("MainWindow", "Include microphone in virtual mix"))
        self.micVolumeLabel.setText(_translate("MainWindow", "Mic Volume"))
        self.micVolumeValue.setText(_translate("MainWindow", "100%"))
